# Generated by Django 2.0.4 on 2020-10-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('knowledge', models.IntegerField(default=3)),
                ('skill_type', models.CharField(choices=[('FRM', 'Framework'), ('LNG', 'Language'), ('DB', 'Database')], max_length=15)),
            ],
        ),
    ]
